export const SET_APP_COLOR = 'SET_APP_COLOR';

export const SET_SELECTED_PROVIDER = 'SET_SELECTED_PROVIDER';

export const SET_GOOGLE_CREDENTIALS = 'SET_GOOGLE_CREDENTIALS';

export const SET_BING_CREDENTIALS = 'SET_BING_CREDENTIALS';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

