export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';
export const SET_APP_COLOR = 'SET_APP_COLOR';
export const SET_SECONDARY_COLOR = 'SET_SECONDARY_COLOR';
export const SET_TERTIARY_COLOR = 'SET_TERTIARY_COLOR';

export const SET_SELECTED_PROVIDER = 'SET_SELECTED_PROVIDER';
export const SET_GOOGLE_CREDENTIALS = 'SET_GOOGLE_CREDENTIALS';
export const SET_BING_CREDENTIALS = 'SET_BING_CREDENTIALS';

export const SET_SELECTED_PALETTE = 'SET_SELECTED_PALETTE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const SET_BUBBLE_INFORMATION = 'SET_BUBBLE_INFORMATION';
export const SET_BUBBLE_ANIMATING = 'SET_BUBBLE_ANIMATING';

export const SET_SEARCH_STATE = 'SET_SEARCH_STATE';
